import { StyleSheet, Platform, Dimensions } from 'react-native';

const { width: screenWidth, height: screenHeight } = Dimensions.get('window');
const CARD_WIDTH = screenWidth - 40;

export const styles = StyleSheet.create({
    // ==================== APP CONTAINER & LAYOUT ====================
    appContainer: {
        flex: 1,
        backgroundColor: '#f8f9fa',
    },
    screenContainer: {
        flex: 1,
        backgroundColor: '#f5f5f5',
    },
    container: {
        flex: 1,
        backgroundColor: '#FFFFFF',
    },
    scrollContainer: {
        flex: 1,
        backgroundColor: '#f5f5f5',
    },
    scrollContent: {
        flexGrow: 1,
        paddingBottom: 100, // Space for bottom navigation
    },
    listContainer: {
        paddingHorizontal: 16,
        paddingTop: 20,
        paddingBottom: 20,
        flex: 1,
    },

    // ==================== HEADERS ====================
    // Main Header (Top Bar)
    mainHeader: {
        paddingTop: Platform.OS === 'ios' ? 50 : 40,
        paddingHorizontal: 16,
        paddingBottom: 12,
        elevation: 4,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 3,
    },
    mainHeaderContent: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
    },
    headerSpacer: {
        width: 36,
    },
    detailHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        backgroundColor: '#075E54',
        paddingHorizontal: 16,
        paddingTop: Platform.OS === 'ios' ? 50 : 40,
        paddingBottom: 12,
        elevation: 4,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 3,
    },
    detailHeaderTitle: {
        fontSize: 18,
        fontWeight: '600',
        color: '#FFFFFF',
        textAlign: 'center',
        flex: 1,
    },
    detailHeaderSpacer: {
        width: 60,
    },

    // Banner Header (Hero)
    header: {
        position: 'relative',
        overflow: 'hidden',
    },
    headerBanner: {
        height: 250,
        borderBottomLeftRadius: 30,
        borderBottomRightRadius: 30,
        overflow: 'hidden',
        position: 'relative',
    },
    headerImage: {
        position: 'absolute',
        top: 0,
        left: 0,
        right: 0,
        bottom: 0,
        width: '100%',
        height: '100%',
        opacity: 1,
    },
    headerOverlay: {
        position: 'absolute',
        top: 0,
        left: 0,
        right: 0,
        bottom: 0,
        width: '100%',
        height: '100%',
        backgroundColor: 'rgba(0, 0, 0, 0.4)',
    },
    headerContent: {
        flex: 1,
        paddingHorizontal: 20,
        paddingTop: Platform.OS === 'ios' ? 60 : 40,
        paddingBottom: 20,
        position: 'relative',
        zIndex: 1,
    },
    bannerContent: {
        flex: 1,
        paddingHorizontal: 20,
        paddingVertical: 40,
        justifyContent: 'flex-end',
        position: 'relative',
        zIndex: 1,
    },
    headerTopRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 20,
    },
    headerCenter: {
        flex: 1,
        alignItems: 'center',
        marginRight: 60,
    },
    headerTitle: {
        fontSize: 24,
        fontWeight: '600',
        color: '#fff',
    },
    headerSubtitle: {
        fontSize: 14,
        color: 'rgba(255,255,255,0.8)',
        marginTop: 4,
    },
    logoText: {
        color: 'white',
        fontSize: 16,
        fontWeight: '800',
        letterSpacing: 1,
        textAlign: 'center',
        flex: 1,
    },

    // Title Section
    titleSection: {
        paddingHorizontal: 20,
        paddingVertical: 25,
        borderBottomLeftRadius: 30,
        borderBottomRightRadius: 30,
    },
    sectionTitle: {
        fontSize: 28,
        fontWeight: '700',
        color: '#fff',
        marginBottom: 4,
    },
    sectionSubtitle: {
        fontSize: 16,
        color: 'rgba(255, 255, 255, 0.9)',
    },

    // ==================== NAVIGATION ====================
    // Bottom Navigation
    bottomNav: {
        position: 'absolute',
        bottom: 0,
        left: 0,
        right: 0,
        backgroundColor: '#fff',
        flexDirection: 'row',
        justifyContent: 'space-around',
        paddingVertical: 15,
        paddingBottom: Platform.OS === 'ios' ? 25 : 15,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: -2 },
        shadowOpacity: 0.1,
        shadowRadius: 20,
        elevation: 5,
        borderTopWidth: 1,
        borderTopColor: '#f0f0f0',
    },
    navItem: {
        alignItems: 'center',
        padding: 5,
    },
    activeNavItem: {},
    navLabel: {
        fontSize: 12,
        color: '#666',
        marginTop: 5,
        fontWeight: '500',
    },
    activeNavLabel: {
        color: '#008069',
        fontWeight: '600',
    },
    navIconContainer: {
        width: 48,
        height: 48,
        borderRadius: 24,
        backgroundColor: '#f5f5f5',
        alignItems: 'center',
        justifyContent: 'center',
        marginBottom: 4,
    },
    activeNavIconContainer: {
        backgroundColor: '#008069',
        shadowColor: '#008069',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.3,
        shadowRadius: 8,
        elevation: 4,
    },

    // ==================== BACK BUTTONS ====================
    backButton: {
        padding: 8,
        flexDirection: 'row',
        alignItems: 'center',
    },
    detailBackButton: {
        flexDirection: 'row',
        alignItems: 'center',
        padding: 8,
    },
    backIcon: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 4,
    },
    backArrow: {
        width: 12,
        height: 12,
        borderLeftWidth: 2,
        borderTopWidth: 2,
        borderColor: '#fff',
        transform: [{ rotate: '-45deg' }],
    },
    backText: {
        color: '#fff',
        fontSize: 16,
        marginLeft: 2,
        fontWeight: '500',
    },
    detailBackText: {
        color: '#FFFFFF',
        fontSize: 16,
        marginLeft: 8,
        fontWeight: '500',
    },

    // ==================== TABS ====================
    tabContainer: {
        flexDirection: 'row',
        backgroundColor: '#FFFFFF',
        marginTop: -20,
        marginHorizontal: 16,
        borderRadius: 12,
        padding: 8,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 8,
        elevation: 4,
        zIndex: 1,
    },
    tabButton: {
        flex: 1,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        paddingVertical: 12,
        borderRadius: 8,
        borderBottomWidth: 3,
        borderBottomColor: 'transparent',
    },
    activeTabButton: {
        backgroundColor: '#E8F5E9',
        borderBottomColor: '#075E54',
    },
    tabText: {
        fontSize: 14,
        fontWeight: '500',
        color: '#666',
        marginLeft: 8,
    },
    activeTabText: {
        color: '#075E54',
        fontWeight: '600',
    },

    // ==================== CARDS ====================
    // Booking Cards
    bookingCard: {
        backgroundColor: '#fff',
        borderRadius: 16,
        padding: 18,
        marginBottom: 16,
        marginTop: 16,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.08,
        shadowRadius: 12,
        elevation: 3,
        borderLeftWidth: 4,
        borderLeftColor: '#008069',
    },
    bookingCardHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 16,
    },
    bookingCardBody: {
        marginBottom: 16,
    },
    bookingCardFooter: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingTop: 16,
        borderTopWidth: 1,
        borderTopColor: '#f0f0f0',
        gap: 20,
    },

    // Cab Cards
    cabCard: {
        backgroundColor: '#fff',
        borderRadius: 16,
        marginBottom: 16,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.08,
        shadowRadius: 12,
        elevation: 3,
        overflow: 'hidden',
        borderWidth: 1,
        borderColor: '#E0E0E0',
    },
    cabImage: {
        width: '100%',
        height: 160,
    },
    cabInfo: {
        padding: 16,
    },
    cabName: {
        fontSize: 18,
        color: '#333',
        fontWeight: '600',
        marginBottom: 4,
    },
    cabMeta: {
        fontSize: 13,
        color: '#666',
        marginBottom: 12,
    },
    cabSpecs: {
        flexDirection: 'row',
        gap: 12,
        marginBottom: 12,
    },
    specItem: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: 'rgba(0, 128, 105, 0.1)',
        paddingHorizontal: 10,
        paddingVertical: 6,
        borderRadius: 12,
        gap: 4,
    },
    specText: {
        fontSize: 12,
        color: '#008069',
        fontWeight: '500',
    },

    // Vehicle Detail Cards
    vehicleDetailHeaderCard: {
        backgroundColor: '#FFFFFF',
        padding: 16,
        borderRadius: 12,
        marginBottom: 16,
        elevation: 2,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.1,
        shadowRadius: 2,
    },
    vehiclePhotoCard: {
        backgroundColor: '#FFFFFF',
        padding: 16,
        borderRadius: 12,
        marginBottom: 16,
        elevation: 2,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.1,
        shadowRadius: 2,
    },
    infoCard: {
        backgroundColor: '#FFFFFF',
        padding: 16,
        borderRadius: 12,
        marginBottom: 16,
        elevation: 2,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.1,
        shadowRadius: 2,
    },
    logCard: {
        backgroundColor: '#FFFFFF',
        padding: 16,
        borderRadius: 12,
        marginBottom: 12,
        borderWidth: 1,
        borderColor: '#E0E0E0',
    },

    // Section Cards (Detail Page)
    sectionCard: {
        backgroundColor: '#FFFFFF',
        borderRadius: 16,
        padding: 18,
        marginBottom: 16,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.06,
        shadowRadius: 8,
        elevation: 3,
    },
    vehicleInfoCard: {
        backgroundColor: '#FFFFFF',
        borderRadius: 20,
        padding: 20,
        marginBottom: 20,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.08,
        shadowRadius: 12,
        elevation: 4,
    },

    // ==================== VEHICLE INFO ====================
    vehicleInfo: {
        flexDirection: 'row',
        alignItems: 'center',
        flex: 1,
    },
    vehicleName: {
        fontSize: 16,
        fontWeight: '600',
        color: '#333',
        flexShrink: 1,
    },
    vehicleModelText: {
        fontSize: 18,
        fontWeight: '700',
        color: '#000000',
        marginBottom: 4,
    },
    vehicleTitle: {
        fontSize: 28,
        fontWeight: '700',
        color: '#1A202C',
        marginBottom: 8,
    },
    vehiclePlateText: {
        fontSize: 14,
        fontWeight: '600',
        color: '#075E54',
        marginBottom: 8,
    },
    vehiclePlate: {
        fontSize: 20,
        fontWeight: '600',
        color: '#075E54',
        marginBottom: 16,
    },
    plateText: {
        fontSize: 13,
        color: '#666',
        marginTop: 2,
    },
    bookingPlateText: {
        fontSize: 18,
        fontWeight: '600',
        color: '#075E54',
        marginBottom: 8,
    },
    bookingTitleText: {
        fontSize: 22,
        fontWeight: '700',
        color: '#000000',
        marginBottom: 4,
    },

    // Vehicle Meta/Chips
    vehicleMeta: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        gap: 8,
    },
    bookingMeta: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        gap: 8,
    },
    vehicleMetaRow: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        gap: 10,
    },
    metaChip: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#E8F5E9',
        paddingHorizontal: 12,
        paddingVertical: 6,
        borderRadius: 16,
        gap: 4,
    },
    metaBadge: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#F0FDF4',
        paddingHorizontal: 14,
        paddingVertical: 8,
        borderRadius: 20,
        gap: 6,
        borderWidth: 1,
        borderColor: '#BBF7D0',
    },
    metaChipText: {
        fontSize: 12,
        color: '#075E54',
        fontWeight: '500',
    },
    metaBadgeText: {
        fontSize: 14,
        color: '#15803D',
        fontWeight: '600',
    },

    // ==================== VEHICLE IMAGES & AVATARS ====================
    vehicleImage: {
        width: 56,
        height: 56,
        borderRadius: 28,
    },
    vehicleImageSmall: {
        width: 48,
        height: 48,
        borderRadius: 24,
    },
    vehicleImageLarge: {
        width: 80,
        height: 80,
        borderRadius: 40,
    },
    vehicleIconContainer: {
        width: 56,
        height: 56,
        borderRadius: 28,
        backgroundColor: '#E8F5E9',
        justifyContent: 'center',
        alignItems: 'center',
    },
    vehicleIconContainerSmall: {
        width: 48,
        height: 48,
        borderRadius: 24,
        backgroundColor: '#E8F5E9',
        justifyContent: 'center',
        alignItems: 'center',
    },
    vehicleIconContainerLarge: {
        width: 80,
        height: 80,
        borderRadius: 40,
        backgroundColor: '#E8F5E9',
        justifyContent: 'center',
        alignItems: 'center',
    },
    vehicleAvatar: {
        width: 64,
        height: 64,
        borderRadius: 32,
        backgroundColor: '#E8F5E9',
        justifyContent: 'center',
        alignItems: 'center',
        marginRight: 16,
    },

    // ==================== PHOTO CAROUSEL ====================
    photoContainer: {
        width: CARD_WIDTH,
        height: 220,
        borderRadius: 12,
        overflow: 'hidden',
        backgroundColor: '#f5f5f5',
    },
    photo: {
        width: '100%',
        height: '100%',
    },
    scrollViewContent: {
        alignItems: 'center',
    },
    pagination: {
        flexDirection: 'row',
        justifyContent: 'center',
        alignItems: 'center',
        paddingVertical: 12,
    },
    dot: {
        width: 8,
        height: 8,
        borderRadius: 4,
        marginHorizontal: 4,
    },
    activeDot: {
        backgroundColor: '#008069',
        width: 10,
        height: 10,
        borderRadius: 5,
    },
    inactiveDot: {
        backgroundColor: '#C7C7CC',
    },
    editButton: {
        position: 'absolute',
        top: 12,
        right: 12,
        backgroundColor: 'rgba(0, 0, 0, 0.6)',
        borderRadius: 20,
        width: 36,
        height: 36,
        justifyContent: 'center',
        alignItems: 'center',
        zIndex: 10,
    },

    // ==================== STATUS BADGES ====================
    statusBadge: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingHorizontal: 12,
        paddingVertical: 6,
        borderRadius: 16,
        marginLeft: 8,
    },
    statusBadgeSmall: {
        paddingHorizontal: 10,
        paddingVertical: 4,
        borderRadius: 12,
        minWidth: 80,
    },
    statusBadgeContainer: {
        alignItems: 'center',
        marginBottom: 16,
    },
    vehicleStatusBadge: {
        paddingHorizontal: 10,
        paddingVertical: 4,
        borderRadius: 12,
        minWidth: 80,
    },
    statusText: {
        fontSize: 12,
        fontWeight: '600',
        marginLeft: 4,
        textTransform: 'capitalize',
    },
    statusBadgeText: {
        fontSize: 14,
        color: '#FFFFFF',
        fontWeight: '600',
        textTransform: 'uppercase',
        marginLeft: 6,
    },
    statusBadgeSmallText: {
        fontSize: 10,
        color: '#FFFFFF',
        fontWeight: '600',
        textTransform: 'uppercase',
        textAlign: 'center',
    },
    vehicleStatusText: {
        fontSize: 10,
        color: '#FFFFFF',
        fontWeight: '600',
        textAlign: 'center',
    },

    // ==================== STATUS UPDATE SECTIONS ====================
    statusOptions: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        gap: 4,
        marginBottom: 12,
    },
    statusOptionsGrid: {
        gap: 10,
    },
    statusOption: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingHorizontal: 14,
        paddingVertical: 10,
        borderRadius: 20,
        // borderWidth: 2,
        // borderColor: '#e0e0e0',
        backgroundColor: '#fff',
        gap: 6,
        minWidth: '48%',
        justifyContent: 'center',
    },
    statusOptionButton: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        paddingVertical: 14,
        paddingHorizontal: 16,
        borderRadius: 12,
        borderWidth: 2,
        borderColor: '#E2E8F0',
        backgroundColor: '#FFFFFF',
        gap: 8,
    },
    statusOptionSelected: {
        backgroundColor: '#075E54',
        borderColor: '#075E54',
    },
    statusOptionText: {
        fontSize: 12,
        fontWeight: '600',
    },
    statusOptionTextSelected: {
        color: '#FFFFFF',
    },

    // ==================== LOCATION & INFO ROWS ====================
    locationRow: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: 8,
    },
    locationText: {
        fontSize: 14,
        color: '#666',
        marginLeft: 10,
        flex: 1,
    },
    vehicleLocation: {
        fontSize: 12,
        color: '#666',
    },
    arrowContainer: {
        marginLeft: 8,
        marginBottom: 8,
    },
    dateTimeInfo: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 6,
    },
    dateTimeInfoText: {
        fontSize: 14,
        color: '#666',
        fontWeight: '500',
    },

    // ==================== BUTTONS ====================
    updateButton: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: '#008069',
        paddingVertical: 14,
        paddingHorizontal: 20,
        borderRadius: 12,
        gap: 8,
        shadowColor: '#008069',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.3,
        shadowRadius: 8,
        elevation: 3,
    },
    updateButtonText: {
        fontSize: 16,
        color: '#fff',
        fontWeight: '600',
    },
    searchBtn: {
        backgroundColor: '#00d285',
        padding: 16,
        borderRadius: 12,
        alignItems: 'center',
        marginTop: 20,
        shadowColor: '#00d285',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.3,
        shadowRadius: 8,
        elevation: 3,
    },
    searchBtnText: {
        color: '#fff',
        fontSize: 16,
        fontWeight: '600',
    },
    disabledBtn: {
        opacity: 0.5,
        shadowOpacity: 0,
        elevation: 0,
    },
    actionButtonsContainer: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        backgroundColor: '#FFFFFF',
        padding: 16,
        borderRadius: 12,
        elevation: 2,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.1,
        shadowRadius: 2,
    },
    actionButton: {
        alignItems: 'center',
        padding: 8,
        minWidth: 70,
    },
    actionButtonText: {
        fontSize: 12,
        color: '#075E54',
        marginTop: 4,
        textAlign: 'center',
    },

    // ==================== FORM ELEMENTS ====================
    formGroup: {
        marginBottom: 16,
    },
    formLabel: {
        fontSize: 14,
        fontWeight: '600',
        color: '#333',
        marginBottom: 8,
    },
    formInput: {
        backgroundColor: '#fff',
        borderWidth: 2,
        borderColor: '#e0e0e0',
        borderRadius: 12,
        paddingHorizontal: 16,
        paddingVertical: 14,
        fontSize: 16,
        color: '#333',
    },
    inputContainer: {
        flexDirection: 'row',
        alignItems: 'flex-start',
        backgroundColor: '#f8f9fa',
        borderRadius: 12,
        paddingHorizontal: 12,
        borderWidth: 1.5,
        borderColor: '#e0e0e0',
    },
    textInput: {
        flex: 1,
        padding: 14,
        fontSize: 15,
        color: '#333',
        minHeight: 48,
    },
    descriptionInput: {
        flex: 1,
        padding: 16,
        fontSize: 16,
        color: '#000000',
        minHeight: 100,
        textAlignVertical: 'top',
    },
    inputIcon: {
        marginTop: 14,
        marginRight: 8,
    },
    dateTimeRow: {
        flexDirection: 'row',
        gap: 10,
    },
    dateTimeInput: {
        flex: 1,
        backgroundColor: '#fff',
        borderWidth: 2,
        borderColor: '#e0e0e0',
        borderRadius: 12,
        paddingHorizontal: 12,
        paddingVertical: 12,
        flexDirection: 'row',
        alignItems: 'center',
    },
    dateTimeText: {
        fontSize: 14,
        color: '#333',
        marginLeft: 8,
        fontWeight: '500',
    },
    dateButton: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#F5F5F5',
        borderRadius: 12,
        padding: 16,
    },
    dateButtonText: {
        flex: 1,
        fontSize: 16,
        color: '#000000',
    },
    dateButtonPlaceholder: {
        color: '#888',
    },

    // ==================== STEP ELEMENTS ====================
    formStep: {
        backgroundColor: '#fff',
        borderRadius: 16,
        padding: 20,
        marginBottom: 20,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.08,
        shadowRadius: 15,
        elevation: 3,
    },
    stepHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: 20,
    },
    stepIcon: {
        width: 52,
        height: 52,
        borderRadius: 26,
        backgroundColor: '#00d285',
        alignItems: 'center',
        justifyContent: 'center',
        marginRight: 16,
    },
    stepTitle: {
        fontSize: 20,
        color: '#333',
        fontWeight: '600',
    },
    stepSubtitle: {
        fontSize: 14,
        color: '#666',
        marginTop: 4,
    },

    // ==================== CHAT ITEMS ====================
    chatItem: {
        flexDirection: 'row',
        padding: 16,
        backgroundColor: '#FFFFFF',
        borderRadius: 12,
        marginBottom: 12,
        borderWidth: 1,
        borderColor: '#E0E0E0',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.05,
        shadowRadius: 4,
        elevation: 2,
    },
    avatarContainer: {
        position: 'relative',
        marginRight: 16,
    },
    avatar: {
        width: 56,
        height: 56,
        borderRadius: 28,
        justifyContent: 'center',
        alignItems: 'center',
    },
    onlineIndicator: {
        position: 'absolute',
        bottom: 2,
        right: 2,
        width: 14,
        height: 14,
        borderRadius: 7,
        backgroundColor: '#25D366',
        borderWidth: 2,
        borderColor: '#FFFFFF',
    },
    chatContent: {
        flex: 1,
        justifyContent: 'center',
    },
    chatHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 6,
    },
    chatName: {
        fontSize: 16,
        fontWeight: '600',
        color: '#000000',
        flex: 1,
    },
    chatTime: {
        fontSize: 12,
        color: '#666',
    },
    chatMessage: {
        marginBottom: 8,
    },
    messageText: {
        fontSize: 14,
        color: '#666',
        lineHeight: 20,
    },
    boldText: {
        fontWeight: '600',
        color: '#000000',
    },
    chatFooter: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
    },

    // ==================== DETAIL PAGE ====================
    detailPageContainer: {
        flex: 1,
        backgroundColor: '#F5F5F5',
    },
    detailPageContent: {
        paddingHorizontal: 16,
        paddingTop: 16,
        paddingBottom: 32,
    },
    vehicleDetailHeader: {
        flexDirection: 'row',
    },
    vehicleDetailInfo: {
        flex: 1,
        justifyContent: 'center',
    },
    bookingDetailHeader: {
        flexDirection: 'row',
    },
    bookingDetailInfo: {
        flex: 1,
        justifyContent: 'center',
    },
    cardHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: 16,
        gap: 8,
    },
    cardTitle: {
        fontSize: 18,
        fontWeight: '600',
        color: '#000000',
    },
    infoGrid: {
        gap: 12,
    },
    bookingInfoGrid: {
        gap: 12,
    },
    infoRow: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    infoLabel: {
        fontSize: 14,
        color: '#666',
        marginLeft: 8,
        marginRight: 4,
        width: 80,
    },
    infoValue: {
        fontSize: 14,
        color: '#000000',
        fontWeight: '500',
        flex: 1,
    },
    logHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'flex-start',
        marginBottom: 12,
    },
    logHeaderLeft: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 8,
    },
    logCost: {
        fontSize: 18,
        fontWeight: '700',
        color: '#075E54',
    },
    logDate: {
        fontSize: 12,
        color: '#666',
    },
    logQuantity: {
        fontSize: 14,
        color: '#666',
        marginTop: 2,
    },
    logDescription: {
        fontSize: 14,
        color: '#000000',
        lineHeight: 20,
        marginBottom: 12,
    },
    logDetails: {
        gap: 8,
    },
    logDetailRow: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 6,
    },
    logDetail: {
        fontSize: 13,
        color: '#666',
    },
    fuelDetails: {
        flexDirection: 'row',
        justifyContent: 'center',
        backgroundColor: '#F5F5F5',
        padding: 12,
        borderRadius: 8,
        marginBottom: 12,
    },
    fuelDetailItem: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 6,
    },
    fuelDetailValue: {
        fontSize: 16,
        fontWeight: '600',
        color: '#075E54',
    },
    detailContentContainer: {
        marginTop: -30,
        borderTopLeftRadius: 30,
        borderTopRightRadius: 30,
        backgroundColor: '#F8F9FA',
        paddingTop: 24,
        paddingHorizontal: 16,
        paddingBottom: 32,
    },
    sectionHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: 16,
        gap: 10,
    },
    sectionDivider: {
        height: 1,
        backgroundColor: '#E2E8F0',
        marginVertical: 12,
    },
    infoIconContainer: {
        width: 36,
        height: 36,
        borderRadius: 18,
        backgroundColor: '#F0FDF4',
        justifyContent: 'center',
        alignItems: 'center',
        marginRight: 12,
    },

    // ==================== MODAL STYLES ====================
    modalOverlay: {
        flex: 1,
        backgroundColor: 'rgba(0,0,0,0.5)',
        justifyContent: 'center',
        alignItems: 'center',
    },
    keyboardAvoidingView: {
        width: '100%',
        alignItems: 'center',
    },
    modalContainer: {
        backgroundColor: 'white',
        borderRadius: 10,
        width: '90%',
        maxHeight: Dimensions.get('window').height * 0.8,
        overflow: 'hidden',
        marginTop: Platform.OS === 'ios' ? 40 : 20,
    },
    modalScrollContent: {
        padding: 20,
        paddingTop: 10,
    },
    modalHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        padding: 16,
        borderBottomWidth: 1,
        borderBottomColor: '#E0E0E0',
    },
    modalCloseButton: {
        width: 40,
        height: 40,
        borderRadius: 20,
        backgroundColor: '#F5F5F5',
        alignItems: 'center',
        justifyContent: 'center',
    },
    modalTitle: {
        fontSize: 18,
        fontWeight: '600',
        color: '#075E54',
    },
    buttonIcon: {
        marginRight: 8,
    },
    documentButton: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#F5F5F5',
        borderRadius: 12,
        padding: 12,
    },
    documentButtonText: {
        flex: 1,
        fontSize: 16,
        color: '#000000',
    },
    documentInfo: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        backgroundColor: '#E8F5E9',
        padding: 12,
        borderRadius: 8,
        marginTop: 8,
        width: '82%',
        marginRight: 12,
        paddingRight: 30,
    },
    documentRow: {
        flexDirection: 'row',
        alignItems: 'center',
        flex: 1,
    },
    documentName: {
        fontSize: 12,
        color: '#075E54',
        marginLeft: 8,
        flex: 1,
    },
    removeDocumentButton: {
        padding: 4,
    },
    modalButtons: {
        flexDirection: 'row',
        gap: 12,
        marginTop: 24,
    },
    modalCancelButton: {
        flex: 1,
        backgroundColor: '#F5F5F5',
        padding: 16,
        borderRadius: 12,
        alignItems: 'center',
        borderWidth: 1,
        borderColor: '#E0E0E0',
    },
    modalCancelText: {
        fontSize: 16,
        color: '#666',
        fontWeight: '600',
    },
    modalSubmitButton: {
        flex: 1,
        backgroundColor: '#075E54',
        padding: 16,
        borderRadius: 12,
        alignItems: 'center',
        justifyContent: 'center',
        minHeight: 52,
    },
    modalSubmitButtonDisabled: {
        backgroundColor: '#CCCCCC',
    },
    modalSubmitText: {
        fontSize: 16,
        color: '#FFFFFF',
        fontWeight: '600',
    },

    // ==================== LOADING & EMPTY STATES ====================
    loadingContainer: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        paddingVertical: 60,
        backgroundColor: '#f5f5f5',
    },
    loadingText: {
        fontSize: 16,
        color: '#666',
        marginTop: 12,
        fontWeight: '500',
    },
    emptyStateContainer: {
        alignItems: 'center',
        paddingVertical: 60,
        paddingHorizontal: 20,
        backgroundColor: '#f5f5f5',
    },
    emptyContainer: {
        alignItems: 'center',
        paddingVertical: 60,
    },
    emptyState: {
        alignItems: 'center',
        paddingVertical: 40,
    },
    emptyIconCircle: {
        width: 100,
        height: 100,
        borderRadius: 50,
        backgroundColor: '#E8F5E9',
        alignItems: 'center',
        justifyContent: 'center',
        marginBottom: 20,
    },
    emptyStateCard: {
        backgroundColor: '#fff',
        borderRadius: 20,
        padding: 32,
        alignItems: 'center',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.1,
        shadowRadius: 12,
        elevation: 4,
        width: '100%',
        maxWidth: 400,
    },
    emptyIconContainer: {
        width: 120,
        height: 120,
        borderRadius: 60,
        backgroundColor: '#F7FAFC',
        alignItems: 'center',
        justifyContent: 'center',
        marginBottom: 24,
    },
    emptyStateTitle: {
        fontSize: 20,
        fontWeight: '600',
        color: '#333',
        marginBottom: 8,
        textAlign: 'center',
    },
    emptyTitle: {
        fontSize: 20,
        fontWeight: '600',
        color: '#666',
        marginTop: 16,
        marginBottom: 8,
    },
    emptyStateText: {
        fontSize: 15,
        color: '#666',
        textAlign: 'center',
        lineHeight: 22,
    },
    emptyStateSubtext: {
        fontSize: 14,
        color: '#999',
        textAlign: 'center',
    },
    emptySubtitle: {
        fontSize: 14,
        color: '#999',
        textAlign: 'center',
        paddingHorizontal: 40,
    },
    emptyStateMessage: {
        fontSize: 16,
        color: '#4A5568',
        textAlign: 'center',
        lineHeight: 24,
        marginBottom: 8,
    },
    emptyStateSuggestion: {
        fontSize: 14,
        color: '#718096',
        textAlign: 'center',
        lineHeight: 20,
    },

    // ==================== HERO IMAGE ====================
    heroImageContainer: {
        width: '100%',
        height: 280,
        backgroundColor: '#E8F5E9',
        position: 'relative',
    },
    heroImage: {
        width: '100%',
        height: '100%',
    },
    heroOverlay: {
        position: 'absolute',
        bottom: 0,
        left: 0,
        right: 0,
        backgroundColor: 'rgba(0,0,0,0.6)',
        padding: 20,
    },
    heroPlaceholder: {
        width: '100%',
        height: '100%',
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: '#E8F5E9',
    },

    // ==================== LISTS ====================
    cabsListContent: {
        padding: 16,
    },
    vehicleFooter: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginTop: 8,
    },
    previousBookingsContainer: {
        marginTop: 24,
    },
    documentSection: {
        marginTop: 12,
        paddingTop: 12,
        borderTopWidth: 1,
        borderTopColor: '#F0F0F0',
    },

    documentCard: {
        backgroundColor: '#F8F9FA',
        borderRadius: 12,
        padding: 12,
        borderWidth: 1,
        borderColor: '#E8E8E8',
        display: 'flex',
        flexDirection: 'row',

    },

    documentTextContainer: {
        marginLeft: 0,
        marginTop: 3,
    },

    documentType: {
        fontSize: 12,
        color: '#718096',
        textTransform: 'uppercase',
    },

    documentActions: {
        flexDirection: 'row',
        gap: 8,
    },
    downloadButtonText: {
        color: '#FFFFFF',
    },
    viewButton: {
        height: 45,
        marginTop: 9,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        borderRadius: 8,
        backgroundColor: '#FFFFFF',
        borderWidth: 1,
        borderColor: '#008069',
    },
    downloadButton: {
        backgroundColor: '#008069',
        borderColor: '#008069',
        height: 45,
        marginTop: 9,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        borderRadius: 8,
        marginLeft: -8,
    },
});