import { StyleSheet, Platform, Dimensions } from 'react-native';

const { width: screenWidth, height: screenHeight } = Dimensions.get('window');
const CARD_WIDTH = screenWidth - 40;

export const styles = StyleSheet.create({
    // ==================== APP CONTAINER & LAYOUT ====================
    screenContainer: {
        flex: 1,
        backgroundColor: '#f5f5f5',
    },
    container: {
        flex: 1,
        backgroundColor: '#FFFFFF',
    },
    scrollContainer: {
        flex: 1,
        backgroundColor: '#f5f5f5',
    },
    scrollContent: {
        flexGrow: 1,
        paddingBottom: 100,
    },

    // ==================== HEADERS ====================
    header: {
        position: 'relative',
        overflow: 'hidden',
    },
    headerBanner: {
        height: 250,
        borderBottomLeftRadius: 30,
        borderBottomRightRadius: 30,
        overflow: 'hidden',
        position: 'relative',
    },
    headerImage: {
        position: 'absolute',
        top: 0,
        left: 0,
        right: 0,
        bottom: 0,
        width: '100%',
        height: '100%',
        opacity: 1,
    },
    headerOverlay: {
        position: 'absolute',
        top: 0,
        left: 0,
        right: 0,
        bottom: 0,
        width: '100%',
        height: '100%',
        backgroundColor: 'rgba(0, 0, 0, 0.4)',
    },
    headerContent: {
        flex: 1,
        paddingHorizontal: 20,
        paddingTop: Platform.OS === 'ios' ? 60 : 40,
        paddingBottom: 20,
        position: 'relative',
        zIndex: 1,
    },
    headerTopRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 20,
    },
    backButton: {
        padding: 8,
    },
    headerCenter: {
        flex: 1,
        alignItems: 'center',
        marginRight: 60,
    },
    logoText: {
        color: 'white',
        fontSize: 16,
        fontWeight: '800',
        letterSpacing: 1,
        textAlign: 'center',
        flex: 1,
    },
    headerTitle: {
        fontSize: 24,
        fontWeight: '600',
        color: '#fff',
    },
    headerSubtitle: {
        fontSize: 14,
        color: 'rgba(255,255,255,0.8)',
        marginTop: 4,
        textAlign: 'center',
    },

    // ==================== CITY SELECTION ====================
    searchBox: {
        padding: 20,
        backgroundColor: '#f5f5f5',
    },
    searchInputWrapper: {
        position: 'relative',
        flexDirection: 'row',
        alignItems: 'center',
    },
    searchInput: {
        backgroundColor: '#fff',
        borderWidth: 2,
        borderColor: '#e0e0e0',
        borderRadius: 25,
        paddingHorizontal: 45,
        paddingVertical: 15,
        fontSize: 16,
        flex: 1,
    },
    searchIcon: {
        position: 'absolute',
        left: 20,
        zIndex: 1,
    },
    citiesGrid: {
        paddingHorizontal: 20,
        flexDirection: 'row',
        flexWrap: 'wrap',
        justifyContent: 'space-between',
    },
    cityCard: {
        width: '30%',
        alignItems: 'center',
        marginBottom: 25,
    },
    cityIconContainer: {
        width: 70,
        height: 70,
        borderRadius: 35,
        backgroundColor: '#fff',
        alignItems: 'center',
        justifyContent: 'center',
        marginBottom: 8,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 8,
        elevation: 3,
    },
    cityIconImage: {
        width: 80,
        height: 80,
        borderRadius: 50,
    },
    cityName: {
        fontSize: 13,
        color: '#333',
        fontWeight: '600',
        textAlign: 'center',
    },
    bottomSpacing: {
        height: 40,
    },

    // ==================== TITLE SECTIONS ====================
    titleSection: {
        paddingHorizontal: 20,
        paddingVertical: 25,
        borderBottomLeftRadius: 30,
        borderBottomRightRadius: 30,
    },
    sectionTitle: {
        fontSize: 28,
        fontWeight: '700',
        color: '#fff',
        marginBottom: 4,
    },
    sectionSubtitle: {
        fontSize: 14,
        color: 'rgba(255, 255, 255, 0.9)',
    },

    // ==================== BACK BUTTONS ====================
    backIcon: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 4,
    },
    backArrow: {
        width: 12,
        height: 12,
        borderLeftWidth: 2,
        borderTopWidth: 2,
        borderColor: '#fff',
        transform: [{ rotate: '-45deg' }],
    },
    backText: {
        color: '#fff',
        fontSize: 14,
        marginLeft: 2,
        fontWeight: '500',
    },
    detailHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        backgroundColor: '#075E54',
        paddingHorizontal: 16,
        paddingTop: Platform.OS === 'ios' ? 50 : 40,
        paddingBottom: 12,
        elevation: 4,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 3,
    },
    detailHeaderTitle: {
        fontSize: 18,
        fontWeight: '600',
        color: '#FFFFFF',
        textAlign: 'center',
        flex: 1,
    },
    detailHeaderSpacer: {
        flexDirection: 'row',
        width: 60,
        justifyContent: 'flex-end',
    },
    detailBackButton: {
        flexDirection: 'row',
        alignItems: 'center',
        padding: 8,
    },

    // ==================== TABS ====================
    tabContainer: {
        flexDirection: 'row',
        backgroundColor: '#FFFFFF',
        marginTop: -20,
        marginHorizontal: 16,
        borderRadius: 12,
        padding: 8,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 8,
        elevation: 4,
        zIndex: 1,
    },
    tabButton: {
        flex: 1,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        paddingVertical: 12,
        borderRadius: 8,
        borderBottomWidth: 3,
        borderBottomColor: 'transparent',
    },
    activeTabButton: {
        backgroundColor: '#E8F5E9',
        borderBottomColor: '#075E54',
    },
    tabText: {
        fontSize: 14,
        fontWeight: '500',
        color: '#666',
        marginLeft: 8,
    },
    activeTabText: {
        color: '#075E54',
        fontWeight: '600',
    },

    // ==================== CARDS ====================
    cabCard: {
        backgroundColor: '#fff',
        borderRadius: 16,
        marginBottom: 16,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.08,
        shadowRadius: 12,
        elevation: 3,
        overflow: 'hidden',
        borderWidth: 1,
        borderColor: '#E0E0E0',
    },
    cabImage: {
        width: '100%',
        height: 160,
    },
    cabInfo: {
        padding: 16,
    },
    cabName: {
        fontSize: 18,
        color: '#333',
        fontWeight: '600',
        marginBottom: 4,
    },
    cabMeta: {
        fontSize: 13,
        color: '#666',
        marginBottom: 12,
    },
    cabSpecs: {
        flexDirection: 'row',
        gap: 12,
        marginBottom: 12,
    },
    specItem: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: 'rgba(0, 128, 105, 0.1)',
        paddingHorizontal: 10,
        paddingVertical: 6,
        borderRadius: 12,
        gap: 4,
    },
    specText: {
        fontSize: 12,
        color: '#008069',
        fontWeight: '500',
    },
    vehicleFooter: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginTop: 8,
    },
    vehicleStatusBadge: {
        paddingHorizontal: 10,
        paddingVertical: 4,
        borderRadius: 12,
        minWidth: 80,
    },
    vehicleStatusText: {
        fontSize: 10,
        color: '#FFFFFF',
        fontWeight: '600',
        textAlign: 'center',
    },
    vehicleLocation: {
        fontSize: 12,
        color: '#666',
    },

    // ==================== VEHICLE DETAIL ====================
    detailPageContainer: {
        flex: 1,
        backgroundColor: '#F5F5F5',
    },
    detailPageContent: {
        paddingHorizontal: 16,
        paddingTop: 16,
        paddingBottom: 32,
    },
    vehiclePhotoCard: {
        backgroundColor: '#FFFFFF',
        padding: 16,
        borderRadius: 12,
        marginBottom: 16,
        elevation: 2,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.1,
        shadowRadius: 2,
    },
    scrollViewContent: {
        alignItems: 'center',
    },
    photoContainer: {
        width: CARD_WIDTH,
        height: 220,
        borderRadius: 12,
        overflow: 'hidden',
        backgroundColor: '#f5f5f5',
    },
    photo: {
        width: '100%',
        height: '100%',
    },
    pagination: {
        flexDirection: 'row',
        justifyContent: 'center',
        alignItems: 'center',
        paddingVertical: 12,
    },
    dot: {
        width: 8,
        height: 8,
        borderRadius: 4,
        marginHorizontal: 4,
    },
    activeDot: {
        backgroundColor: '#008069',
        width: 10,
        height: 10,
        borderRadius: 5,
    },
    inactiveDot: {
        backgroundColor: '#C7C7CC',
    },
    vehicleDetailHeaderCard: {
        backgroundColor: '#FFFFFF',
        padding: 16,
        borderRadius: 12,
        marginBottom: 16,
        elevation: 2,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.1,
        shadowRadius: 2,
    },
    vehicleDetailHeader: {
        flexDirection: 'row',
    },
    vehicleIconContainer: {
        width: 56,
        height: 56,
        borderRadius: 28,
        backgroundColor: '#E8F5E9',
        justifyContent: 'center',
        alignItems: 'center',
        marginRight: 16,
    },
    vehicleDetailInfo: {
        flex: 1,
        justifyContent: 'center',
    },
    vehicleModelText: {
        fontSize: 18,
        fontWeight: '700',
        color: '#000000',
        marginBottom: 4,
    },
    vehiclePlateText: {
        fontSize: 14,
        fontWeight: '600',
        color: '#075E54',
        marginBottom: 8,
    },
    vehicleMeta: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        gap: 8,
    },
    metaChip: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#E8F5E9',
        paddingHorizontal: 12,
        paddingVertical: 6,
        borderRadius: 16,
        gap: 4,
    },
    metaChipText: {
        fontSize: 12,
        color: '#075E54',
        fontWeight: '500',
    },

    // ==================== INFO CARDS ====================
    infoCard: {
        backgroundColor: '#FFFFFF',
        padding: 16,
        borderRadius: 12,
        marginBottom: 16,
        elevation: 2,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.1,
        shadowRadius: 2,
    },
    cardHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: 16,
        gap: 8,
    },
    cardTitle: {
        fontSize: 18,
        fontWeight: '600',
        color: '#000000',
    },
    infoGrid: {
        gap: 12,
    },
    infoRow: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    infoLabel: {
        fontSize: 14,
        color: '#666',
        marginLeft: 8,
        marginRight: 4,
        width: 80,
    },
    infoValue: {
        fontSize: 14,
        color: '#000000',
        fontWeight: '500',
        flex: 1,
    },

    // ==================== STATUS OPTIONS ====================
    statusOptions: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        gap: 4,
        marginBottom: 12,
    },
    statusOption: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingHorizontal: 14,
        paddingVertical: 10,
        borderRadius: 20,
        backgroundColor: '#fff',
        gap: 6,
        minWidth: '48%',
        justifyContent: 'center',
    },
    statusOptionSelected: {
        backgroundColor: '#075E54',
        borderColor: '#075E54',
    },
    statusOptionText: {
        fontSize: 12,
        fontWeight: '600',
    },
    statusOptionTextSelected: {
        color: '#FFFFFF',
    },
    updateButton: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: '#008069',
        paddingVertical: 14,
        paddingHorizontal: 20,
        borderRadius: 12,
        gap: 8,
        shadowColor: '#008069',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.3,
        shadowRadius: 8,
        elevation: 3,
    },
    updateButtonText: {
        fontSize: 16,
        color: '#fff',
        fontWeight: '600',
    },

    // ==================== ACTION BUTTONS ====================
    actionButtonsContainer: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        backgroundColor: '#FFFFFF',
        padding: 16,
        borderRadius: 12,
        elevation: 2,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.1,
        shadowRadius: 2,
    },
    actionButton: {
        alignItems: 'center',
        padding: 8,
        minWidth: 70,
    },
    actionButtonText: {
        fontSize: 12,
        color: '#075E54',
        marginTop: 4,
        textAlign: 'center',
    },

    // ==================== BOOKING CARDS ====================
    bookingCard: {
        backgroundColor: '#fff',
        borderRadius: 16,
        padding: 18,
        marginBottom: 16,
        marginTop: 16,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.08,
        shadowRadius: 12,
        elevation: 3,
        borderLeftWidth: 4,
        borderLeftColor: '#008069',
    },
    bookingCardHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 16,
    },
    vehicleInfo: {
        flexDirection: 'row',
        alignItems: 'center',
        flex: 1,
    },
    vehicleName: {
        fontSize: 16,
        fontWeight: '600',
        color: '#333',
        flexShrink: 1,
    },
    plateText: {
        fontSize: 13,
        color: '#666',
        marginTop: 2,
    },
    statusBadge: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingHorizontal: 12,
        paddingVertical: 6,
        borderRadius: 16,
        marginLeft: 8,
    },
    statusText: {
        fontSize: 12,
        fontWeight: '600',
        marginLeft: 4,
        textTransform: 'capitalize',
    },
    bookingCardBody: {
        marginBottom: 16,
    },
    locationRow: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: 8,
    },
    locationText: {
        fontSize: 14,
        color: '#666',
        marginLeft: 10,
        flex: 1,
    },
    arrowContainer: {
        marginLeft: 8,
        marginBottom: 8,
    },
    bookingCardFooter: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingTop: 16,
        borderTopWidth: 1,
        borderTopColor: '#f0f0f0',
        gap: 20,
    },
    dateTimeInfo: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 6,
    },
    dateTimeInfoText: {
        fontSize: 14,
        color: '#666',
        fontWeight: '500',
    },

    // ==================== VEHICLE IMAGES ====================
    vehicleImage: {
        width: 56,
        height: 56,
        borderRadius: 28,
    },
    vehicleImageLarge: {
        width: 80,
        height: 80,
        borderRadius: 40,
    },
    vehicleIconContainerLarge: {
        width: 80,
        height: 80,
        borderRadius: 40,
        backgroundColor: '#E8F5E9',
        justifyContent: 'center',
        alignItems: 'center',
    },

    // ==================== FORM ELEMENTS ====================
    formGroup: {
        marginBottom: 16,
    },
    formLabel: {
        fontSize: 14,
        fontWeight: '600',
        color: '#333',
        marginBottom: 8,
    },
    inputContainer: {
        flexDirection: 'row',
        alignItems: 'flex-start',
        backgroundColor: '#f8f9fa',
        borderRadius: 12,
        paddingHorizontal: 12,
        borderWidth: 1.5,
        borderColor: '#e0e0e0',
    },
    textInput: {
        flex: 1,
        padding: 14,
        fontSize: 15,
        color: '#333',
        minHeight: 48,
    },
    inputIcon: {
        marginTop: 14,
        marginRight: 8,
    },
    dateTimeInput: {
        flex: 1,
        backgroundColor: '#fff',
        borderWidth: 2,
        borderColor: '#e0e0e0',
        borderRadius: 12,
        paddingHorizontal: 12,
        paddingVertical: 12,
        flexDirection: 'row',
        alignItems: 'center',
    },
    dateTimeText: {
        fontSize: 14,
        color: '#333',
        marginLeft: 8,
        fontWeight: '500',
    },
    descriptionInput: {
        flex: 1,
        padding: 16,
        fontSize: 16,
        color: '#000000',
        minHeight: 100,
        textAlignVertical: 'top',
    },
    dateButton: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#F5F5F5',
        borderRadius: 12,
        padding: 16,
    },
    dateButtonText: {
        flex: 1,
        fontSize: 16,
        color: '#000000',
    },
    dateButtonPlaceholder: {
        color: '#888',
    },
    buttonIcon: {
        marginRight: 8,
    },
    documentButton: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#F5F5F5',
        borderRadius: 12,
        padding: 12,
    },
    documentButtonText: {
        flex: 1,
        fontSize: 16,
        color: '#000000',
    },
    documentInfo: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        backgroundColor: '#E8F5E9',
        padding: 12,
        borderRadius: 8,
        marginTop: 8,
        width: '82%',
        marginRight: 12,
        paddingRight: 30,
    },
    documentRow: {
        flexDirection: 'row',
        alignItems: 'center',
        flex: 1,
    },
    documentName: {
        fontSize: 12,
        color: '#075E54',
        marginLeft: 8,
        flex: 1,
    },
    removeDocumentButton: {
        padding: 4,
    },

    // ==================== BOOKING MODAL SPECIFIC ====================
    selectedUser: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: 'rgba(1,123,249,0.1)',
        paddingHorizontal: 15,
        paddingVertical: 12,
        borderRadius: 12,
        marginBottom: 15,
    },
    userAvatar: {
        width: 40,
        height: 40,
        borderRadius: 20,
        backgroundColor: '#ff5e7a',
        alignItems: 'center',
        justifyContent: 'center',
        marginRight: 12,
    },
    userAvatarText: {
        color: '#fff',
        fontWeight: '600',
        fontSize: 14,
    },
    userInfo: {
        flex: 1,
    },
    userName: {
        color: '#008069',
        fontWeight: '600',
        fontSize: 15,
    },
    userEmail: {
        color: '#666',
        fontSize: 12,
        marginTop: 2,
    },
    searchButton: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#F5F5F5',
        borderRadius: 12,
        padding: 12,
        gap: 8,
    },
    searchButtonText: {
        fontSize: 16,
        color: '#000000',
    },
    searchContainer: {
        marginTop: 8,
    },
    // searchInput: {
    //     backgroundColor: '#fff',
    //     borderWidth: 1,
    //     borderColor: '#e0e0e0',
    //     borderRadius: 12,
    //     paddingHorizontal: 15,
    //     paddingVertical: 12,
    //     fontSize: 15,
    //     color: '#333',
    // },
    loadingContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        padding: 12,
        backgroundColor: '#f8f8f8',
        borderRadius: 12,
        marginTop: 8,
    },
    loadingText: {
        marginLeft: 10,
        color: '#666',
        fontSize: 14,
    },
    resultsList: {
        maxHeight: 200,
        backgroundColor: '#fff',
        borderWidth: 1,
        borderColor: '#e0e0e0',
        borderRadius: 12,
        marginTop: 8,
    },
    userResult: {
        padding: 12,
        flexDirection: 'row',
        alignItems: 'center',
        borderBottomWidth: 1,
        borderBottomColor: '#f0f0f0',
    },
    resultAvatar: {
        width: 36,
        height: 36,
        borderRadius: 18,
        backgroundColor: '#ff5e7a',
        alignItems: 'center',
        justifyContent: 'center',
        marginRight: 12,
    },
    resultAvatarText: {
        color: '#fff',
        fontWeight: '600',
        fontSize: 13,
    },
    resultInfo: {
        flex: 1,
    },
    resultName: {
        fontWeight: '600',
        color: '#333',
        fontSize: 14,
    },
    resultEmail: {
        fontSize: 12,
        color: '#666',
        marginTop: 2,
    },
    noResults: {
        padding: 20,
        backgroundColor: '#f8f8f8',
        borderRadius: 12,
        marginTop: 8,
        alignItems: 'center',
    },
    noResultsText: {
        color: '#666',
        fontSize: 14,
    },

    // ==================== MODAL STYLES ====================
    modalOverlay: {
        flex: 1,
        backgroundColor: 'rgba(0,0,0,0.5)',
        justifyContent: 'center',
        alignItems: 'center',
    },
    keyboardAvoidingView: {
        width: '100%',
        alignItems: 'center',
    },
    modalContainer: {
        backgroundColor: 'white',
        borderRadius: 10,
        width: '90%',
        maxHeight: Dimensions.get('window').height * 0.8,
        overflow: 'hidden',
        marginTop: Platform.OS === 'ios' ? 40 : 20,
    },
    modalScrollContent: {
        padding: 20,
        paddingTop: 10,
    },
    modalHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        padding: 16,
        borderBottomWidth: 1,
        borderBottomColor: '#E0E0E0',
    },
    modalCloseButton: {
        width: 40,
        height: 40,
        borderRadius: 20,
        backgroundColor: '#F5F5F5',
        alignItems: 'center',
        justifyContent: 'center',
    },
    modalTitle: {
        fontSize: 18,
        fontWeight: '600',
        color: '#075E54',
    },
    downloadButton: {
        width: 40,
        height: 40,
        borderRadius: 20,
        backgroundColor: '#F5F5F5',
        alignItems: 'center',
        justifyContent: 'center',
    },
    modalButtons: {
        flexDirection: 'row',
        gap: 12,
        marginTop: 24,
    },
    modalCancelButton: {
        flex: 1,
        backgroundColor: '#F5F5F5',
        padding: 16,
        borderRadius: 12,
        alignItems: 'center',
        borderWidth: 1,
        borderColor: '#E0E0E0',
    },
    modalCancelText: {
        fontSize: 16,
        color: '#666',
        fontWeight: '600',
    },
    modalSubmitButton: {
        flex: 1,
        backgroundColor: '#075E54',
        padding: 16,
        borderRadius: 12,
        alignItems: 'center',
        justifyContent: 'center',
        minHeight: 52,
    },
    modalSubmitButtonDisabled: {
        backgroundColor: '#CCCCCC',
    },
    modalSubmitText: {
        fontSize: 16,
        color: '#FFFFFF',
        fontWeight: '600',
    },

    // ==================== LOG CARDS ====================
    logCard: {
        backgroundColor: '#FFFFFF',
        padding: 16,
        borderRadius: 12,
        marginBottom: 12,
        borderWidth: 1,
        borderColor: '#E0E0E0',
    },
    logHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'flex-start',
        marginBottom: 12,
    },
    logHeaderLeft: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 8,
    },
    logCost: {
        fontSize: 18,
        fontWeight: '700',
        color: '#075E54',
    },
    logDate: {
        fontSize: 12,
        color: '#666',
    },
    logQuantity: {
        fontSize: 14,
        color: '#666',
        marginTop: 2,
    },
    logDescription: {
        fontSize: 14,
        color: '#000000',
        lineHeight: 20,
        marginBottom: 12,
    },
    logDetails: {
        gap: 8,
    },
    logDetailRow: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 6,
    },
    logDetail: {
        fontSize: 13,
        color: '#666',
    },
    fuelDetails: {
        flexDirection: 'row',
        justifyContent: 'center',
        backgroundColor: '#F5F5F5',
        padding: 12,
        borderRadius: 8,
        marginBottom: 12,
    },
    fuelDetailItem: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 6,
    },
    fuelDetailValue: {
        fontSize: 16,
        fontWeight: '600',
        color: '#075E54',
    },
    documentSection: {
        marginTop: 12,
        paddingTop: 12,
        borderTopWidth: 1,
        borderTopColor: '#F0F0F0',
    },
    documentCard: {
        backgroundColor: '#F8F9FA',
        borderRadius: 12,
        padding: 12,
        borderWidth: 1,
        borderColor: '#E8E8E8',
        display: 'flex',
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
    },
    documentTextContainer: {
        marginLeft: 0,
        marginTop: 3,
    },
    documentActions: {
        flexDirection: 'row',
        gap: 8,
    },
    viewButton: {
        height: 45,
        width: 45,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        borderRadius: 8,
        backgroundColor: '#FFFFFF',
        borderWidth: 1,
        borderColor: '#008069',
    },
    // downloadButton: {
    //     backgroundColor: '#008069',
    //     borderColor: '#008069',
    //     height: 45,
    //     width: 45,
    //     flexDirection: 'row',
    //     alignItems: 'center',
    //     justifyContent: 'center',
    //     borderRadius: 8,
    //     marginLeft: 8,
    // },

    // ==================== LOADING & EMPTY STATES ====================
    // loadingContainer: {
    //     flex: 1,
    //     justifyContent: 'center',
    //     alignItems: 'center',
    //     paddingVertical: 60,
    //     backgroundColor: '#f5f5f5',
    // },
    // loadingText: {
    //     fontSize: 16,
    //     color: '#666',
    //     marginTop: 12,
    //     fontWeight: '500',
    // },
    emptyStateContainer: {
        alignItems: 'center',
        paddingVertical: 60,
        paddingHorizontal: 20,
        backgroundColor: '#f5f5f5',
    },
    emptyIconCircle: {
        width: 100,
        height: 100,
        borderRadius: 50,
        backgroundColor: '#E8F5E9',
        alignItems: 'center',
        justifyContent: 'center',
        marginBottom: 20,
    },
    emptyStateCard: {
        backgroundColor: '#fff',
        borderRadius: 20,
        padding: 32,
        alignItems: 'center',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.1,
        shadowRadius: 12,
        elevation: 4,
        width: '100%',
        maxWidth: 400,
    },
    emptyIconContainer: {
        width: 120,
        height: 120,
        borderRadius: 60,
        backgroundColor: '#F7FAFC',
        alignItems: 'center',
        justifyContent: 'center',
        marginBottom: 24,
    },
    emptyStateTitle: {
        fontSize: 20,
        fontWeight: '600',
        color: '#333',
        marginBottom: 8,
        textAlign: 'center',
    },
    emptyStateText: {
        fontSize: 15,
        color: '#666',
        textAlign: 'center',
        lineHeight: 22,
    },
    emptyStateSubtext: {
        fontSize: 14,
        color: '#999',
        textAlign: 'center',
    },
    emptyStateMessage: {
        fontSize: 16,
        color: '#4A5568',
        textAlign: 'center',
        lineHeight: 24,
        marginBottom: 8,
    },
    emptyState: {
        alignItems: 'center',
        paddingVertical: 40,
    },

    // ==================== LISTS ====================
    cabsListContent: {
        padding: 16,
    },
    searchBtn: {
        backgroundColor: '#00d285',
        padding: 16,
        borderRadius: 12,
        alignItems: 'center',
        marginTop: 20,
        shadowColor: '#00d285',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.3,
        shadowRadius: 8,
        elevation: 3,
    },
    searchBtnText: {
        color: '#fff',
        fontSize: 16,
        fontWeight: '600',
    },
    disabledBtn: {
        opacity: 0.5,
        shadowOpacity: 0,
        elevation: 0,
    },
    formSection: {
        backgroundColor: '#FFFFFF',
        borderRadius: 12,
        padding: 16,
        marginBottom: 16,
        marginHorizontal: 16,
        elevation: 2,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.1,
        shadowRadius: 2,
    },
    formInput: {
        backgroundColor: '#F8F9FA',
        borderWidth: 1.5,
        borderColor: '#E0E0E0',
        borderRadius: 12,
        paddingHorizontal: 16,
        paddingVertical: 14,
        fontSize: 16,
        color: '#333',
    },
    optionsContainer: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        gap: 8,
        marginTop: 4,
    },
    optionButton: {
        paddingHorizontal: 16,
        paddingVertical: 10,
        borderRadius: 20,
        backgroundColor: '#F5F5F5',
        borderWidth: 1.5,
        borderColor: '#E0E0E0',
        minWidth: 100,
        alignItems: 'center',
    },
    optionButtonSelected: {
        backgroundColor: '#E8F5E9',
        borderColor: '#075E54',
    },
    optionButtonText: {
        fontSize: 14,
        fontWeight: '500',
        color: '#666',
    },
    optionButtonTextSelected: {
        color: '#075E54',
        fontWeight: '600',
    },
    documentGroup: {
        marginBottom: 16,
    },
    documentSelected: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#E8F5E9',
        borderRadius: 12,
        padding: 12,
        borderWidth: 1.5,
        borderColor: '#075E54',
        gap: 12,
    },
    // documentButton: {
    //     flexDirection: 'row',
    //     alignItems: 'center',
    //     backgroundColor: '#F5F5F5',
    //     borderRadius: 12,
    //     padding: 16,
    //     borderWidth: 1.5,
    //     borderColor: '#E0E0E0',
    //     borderStyle: 'dashed',
    //     gap: 12,
    // },
    // documentButtonText: {
    //     fontSize: 16,
    //     color: '#075E54',
    //     fontWeight: '500',
    //     flex: 1,
    // },
    photoButton: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: '#F5F5F5',
        borderRadius: 12,
        padding: 16,
        borderWidth: 1.5,
        borderColor: '#E0E0E0',
        borderStyle: 'dashed',
        gap: 12,
        marginBottom: 12,
    },
    photoButtonText: {
        fontSize: 16,
        color: '#075E54',
        fontWeight: '500',
    },
    photosContainer: {
        gap: 8,
        marginTop: 8,
    },
    photoItem: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#F8F9FA',
        borderRadius: 12,
        padding: 12,
        borderWidth: 1,
        borderColor: '#E0E0E0',
        gap: 12,
    },
    photoName: {
        fontSize: 14,
        color: '#333',
        flex: 1,
    },
    submitButton: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: '#075E54',
        borderRadius: 12,
        paddingVertical: 18,
        paddingHorizontal: 24,
        marginHorizontal: 16,
        marginBottom: 32,
        marginTop: 8,
        gap: 12,
        shadowColor: '#075E54',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.3,
        shadowRadius: 8,
        elevation: 4,
    },
    submitButtonDisabled: {
        backgroundColor: '#A0A0A0',
        shadowOpacity: 0,
        elevation: 0,
    },
    submitButtonText: {
        fontSize: 18,
        color: '#FFFFFF',
        fontWeight: '600',
    },
});