import { StyleSheet, Platform, Dimensions } from 'react-native';

const { width: screenWidth, height: screenHeight } = Dimensions.get('window');
const CARD_WIDTH = screenWidth - 40;
const IMAGE_SLOT_WIDTH = (screenWidth - 80) / 3;

export const styles = StyleSheet.create({
    // ==================== APP CONTAINER & LAYOUT ====================
    screenContainer: {
        flex: 1,
        backgroundColor: '#F0F2F5',
    },
    container: {
        flex: 1,
        backgroundColor: '#FFFFFF',
    },
    scrollContainer: {
        flex: 1,
        backgroundColor: '#F0F2F5',
    },
    scrollContent: {
        flexGrow: 1,
        paddingBottom: 100,
    },

    // ==================== HEADERS ====================
    header: {
        position: 'relative',
        overflow: 'hidden',
    },
    headerBanner: {
        height: 250,
        borderBottomLeftRadius: 30,
        borderBottomRightRadius: 30,
        overflow: 'hidden',
        position: 'relative',
    },
    headerImage: {
        position: 'absolute',
        top: 0,
        left: 0,
        right: 0,
        bottom: 0,
        width: '100%',
        height: '100%',
        opacity: 1,
    },
    headerOverlay: {
        position: 'absolute',
        top: 0,
        left: 0,
        right: 0,
        bottom: 0,
        width: '100%',
        height: '100%',
        backgroundColor: 'rgba(0, 0, 0, 0.4)',
    },
    headerContent: {
        flex: 1,
        paddingHorizontal: 20,
        paddingTop: Platform.OS === 'ios' ? 60 : 40,
        paddingBottom: 20,
        position: 'relative',
        zIndex: 1,
    },
    headerTopRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 20,
    },
    backButton: {
        padding: 8,
    },
    headerCenter: {
        flex: 1,
        alignItems: 'center',
        marginRight: 20,
    },
    logoText: {
        color: 'white',
        fontSize: 16,
        fontWeight: '800',
        letterSpacing: 1,
        textAlign: 'center',
        flex: 1,
    },
    headerTitle: {
        fontSize: 24,
        fontWeight: '600',
        color: '#fff',
    },
    headerSubtitle: {
        fontSize: 14,
        color: 'rgba(255,255,255,0.8)',
        marginTop: 4,
        textAlign: 'center',
    },

    // ==================== CITY SELECTION ====================
    searchBox: {
        padding: 20,
        backgroundColor: '#F0F2F5',
    },
    searchInputWrapper: {
        position: 'relative',
        flexDirection: 'row',
        alignItems: 'center',
    },
    searchInput: {
        backgroundColor: '#fff',
        borderWidth: 1,
        borderColor: '#E9EDEF',
        borderRadius: 25,
        paddingHorizontal: 45,
        paddingVertical: 15,
        fontSize: 16,
        flex: 1,
    },
    searchIcon: {
        position: 'absolute',
        left: 20,
        zIndex: 1,
    },
    citiesGrid: {
        paddingHorizontal: 20,
        flexDirection: 'row',
        flexWrap: 'wrap',
        justifyContent: 'space-between',
    },
    cityCard: {
        width: '30%',
        alignItems: 'center',
        marginBottom: 25,
    },
    cityIconContainer: {
        width: 70,
        height: 70,
        borderRadius: 35,
        backgroundColor: '#fff',
        alignItems: 'center',
        justifyContent: 'center',
        marginBottom: 8,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 8,
        elevation: 3,
    },
    cityIconImage: {
        width: 80,
        height: 80,
        borderRadius: 50,
    },
    cityName: {
        fontSize: 13,
        color: '#333',
        fontWeight: '600',
        textAlign: 'center',
    },
    bottomSpacing: {
        height: 40,
    },

    // ==================== TITLE SECTIONS ====================
    titleSection: {
        paddingHorizontal: 20,
        paddingVertical: 25,
        borderBottomLeftRadius: 30,
        borderBottomRightRadius: 30,
    },
    sectionTitle: {
        fontSize: 28,
        fontWeight: '700',
        color: '#fff',
        marginBottom: 4,
    },
    sectionSubtitle: {
        fontSize: 14,
        color: 'rgba(255, 255, 255, 0.9)',
    },

    // ==================== BACK BUTTONS ====================
    backIcon: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,  // Increase from 4 to 8 for more space
},
    backArrow: {
    width: 14,
    height: 14,
    borderLeftWidth: 3,
    borderTopWidth: 3,
    borderColor: '#fff',
    transform: [{ rotate: '-45deg' }],
},
    backText: {
    color: '#fff',
    fontSize: 14,
    marginLeft: 2,  // More space from arrow
    fontWeight: '600',  // Bolder
},
    detailHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        backgroundColor: '#008069',
        paddingHorizontal: 16,
        paddingTop: Platform.OS === 'ios' ? 50 : 40,
        paddingBottom: 12,
        elevation: 4,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 3,
    },
    detailHeaderTitle: {
        fontSize: 18,
        fontWeight: '600',
        color: '#FFFFFF',
        textAlign: 'center',
        flex: 1,
    },
    detailHeaderSpacer: {
        flexDirection: 'row',
        width: 60,
        justifyContent: 'flex-end',
    },
    detailBackButton: {
        flexDirection: 'row',
        alignItems: 'center',
        padding: 8,
    },

    // ==================== TABS ====================
    tabContainer: {
        flexDirection: 'row',
        backgroundColor: '#FFFFFF',
        marginTop: -20,
        marginHorizontal: 16,
        borderRadius: 12,
        padding: 8,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 8,
        elevation: 4,
        zIndex: 1,
    },
    tabButton: {
        flex: 1,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        paddingVertical: 12,
        borderRadius: 8,
        borderBottomWidth: 3,
        borderBottomColor: 'transparent',
    },
    activeTabButton: {
        backgroundColor: '#E8F5E9',
        borderBottomColor: '#008069',
    },
    tabText: {
        fontSize: 14,
        fontWeight: '500',
        color: '#666',
        marginLeft: 8,
    },
    activeTabText: {
        color: '#008069',
        fontWeight: '600',
    },

    // ==================== CARDS ====================
    cabCard: {
        backgroundColor: '#fff',
        borderRadius: 16,
        marginBottom: 16,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.08,
        shadowRadius: 12,
        elevation: 3,
        overflow: 'hidden',
        borderWidth: 1,
        borderColor: '#E9EDEF',
    },
    cabImage: {
        width: '100%',
        height: 160,
    },
    cabInfo: {
        padding: 16,
    },
    cabName: {
        fontSize: 18,
        color: '#333',
        fontWeight: '600',
        marginBottom: 4,
    },
    cabMeta: {
        fontSize: 13,
        color: '#666',
        marginBottom: 12,
    },
    cabSpecs: {
        flexDirection: 'row',
        gap: 12,
        marginBottom: 12,
    },
    specItem: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: 'rgba(0, 128, 105, 0.1)',
        paddingHorizontal: 10,
        paddingVertical: 6,
        borderRadius: 12,
        gap: 4,
    },
    specText: {
        fontSize: 12,
        color: '#008069',
        fontWeight: '500',
    },
    vehicleFooter: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginTop: 8,
    },
    vehicleStatusBadge: {
        paddingHorizontal: 10,
        paddingVertical: 4,
        borderRadius: 12,
        minWidth: 80,
    },
    vehicleStatusText: {
        fontSize: 10,
        color: '#FFFFFF',
        fontWeight: '600',
        textAlign: 'center',
    },
    vehicleLocation: {
        fontSize: 12,
        color: '#666',
    },

    // ==================== VEHICLE DETAIL ====================
    detailPageContainer: {
        flex: 1,
        backgroundColor: '#F0F2F5',
    },
    detailPageContent: {
        paddingHorizontal: 16,
        paddingTop: 16,
        paddingBottom: 32,
    },
    vehiclePhotoCard: {
        backgroundColor: '#FFFFFF',
        padding: 16,
        borderRadius: 12,
        marginBottom: 16,
        elevation: 2,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.1,
        shadowRadius: 2,
    },
    scrollViewContent: {
        alignItems: 'center',
    },
    photoContainer: {
        width: CARD_WIDTH,
        height: 220,
        borderRadius: 12,
        overflow: 'hidden',
        backgroundColor: '#f5f5f5',
    },
    photo: {
        width: '100%',
        height: '100%',
    },
    pagination: {
        flexDirection: 'row',
        justifyContent: 'center',
        alignItems: 'center',
        paddingVertical: 12,
    },
    dot: {
        width: 8,
        height: 8,
        borderRadius: 4,
        marginHorizontal: 4,
    },
    activeDot: {
        backgroundColor: '#008069',
        width: 10,
        height: 10,
        borderRadius: 5,
    },
    inactiveDot: {
        backgroundColor: '#C7C7CC',
    },
    vehicleDetailHeaderCard: {
        backgroundColor: '#FFFFFF',
        padding: 16,
        borderRadius: 12,
        marginBottom: 16,
        elevation: 2,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.1,
        shadowRadius: 2,
    },
    vehicleDetailHeader: {
        flexDirection: 'row',
    },
    vehicleIconContainer: {
        width: 56,
        height: 56,
        borderRadius: 28,
        backgroundColor: '#E8F5E9',
        justifyContent: 'center',
        alignItems: 'center',
        marginRight: 16,
    },
    vehicleDetailInfo: {
        flex: 1,
        justifyContent: 'center',
    },
    vehicleModelText: {
        fontSize: 18,
        fontWeight: '700',
        color: '#000000',
        marginBottom: 4,
    },
    vehiclePlateText: {
        fontSize: 14,
        fontWeight: '600',
        color: '#008069',
        marginBottom: 8,
    },
    vehicleMeta: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        gap: 8,
    },
    metaChip: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#E8F5E9',
        paddingHorizontal: 12,
        paddingVertical: 6,
        borderRadius: 16,
        gap: 4,
    },
    metaChipText: {
        fontSize: 12,
        color: '#008069',
        fontWeight: '500',
    },

    // ==================== INFO CARDS ====================
    infoCard: {
        backgroundColor: '#FFFFFF',
        padding: 16,
        borderRadius: 12,
        marginBottom: 16,
        elevation: 2,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.1,
        shadowRadius: 2,
    },
    cardHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: 16,
        gap: 8,
    },
    cardTitle: {
        fontSize: 18,
        fontWeight: '600',
        color: '#000000',
    },
    infoGrid: {
        gap: 12,
    },
    infoRow: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    infoLabel: {
        fontSize: 14,
        color: '#666',
        marginLeft: 8,
        marginRight: 4,
        width: 80,
    },
    infoValue: {
        fontSize: 14,
        color: '#000000',
        fontWeight: '500',
        flex: 1,
    },

    // ==================== STATUS OPTIONS ====================
    statusOptions: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        gap: 4,
        marginBottom: 12,
    },
    statusOption: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingHorizontal: 14,
        paddingVertical: 10,
        borderRadius: 20,
        backgroundColor: '#fff',
        gap: 6,
        minWidth: '48%',
        justifyContent: 'center',
    },
    statusOptionSelected: {
        backgroundColor: '#008069',
        borderColor: '#008069',
    },
    statusOptionText: {
        fontSize: 12,
        fontWeight: '600',
    },
    statusOptionTextSelected: {
        color: '#FFFFFF',
    },
    updateButton: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: '#008069',
        paddingVertical: 14,
        paddingHorizontal: 20,
        borderRadius: 12,
        gap: 8,
        shadowColor: '#008069',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.3,
        shadowRadius: 8,
        elevation: 3,
    },
    updateButtonText: {
        fontSize: 16,
        color: '#fff',
        fontWeight: '600',
    },

    // ==================== ACTION BUTTONS ====================
    actionButtonsContainer: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        backgroundColor: '#FFFFFF',
        padding: 16,
        borderRadius: 12,
        elevation: 2,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.1,
        shadowRadius: 2,
    },
    actionButton: {
        alignItems: 'center',
        padding: 8,
        minWidth: 70,
    },
    actionButtonText: {
        fontSize: 12,
        color: '#008069',
        marginTop: 4,
        textAlign: 'center',
    },

    // ==================== BOOKING CARDS ====================
    bookingCard: {
        backgroundColor: '#fff',
        borderRadius: 16,
        padding: 18,
        marginBottom: 16,
        marginTop: 16,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.08,
        shadowRadius: 12,
        elevation: 3,
        borderLeftWidth: 4,
        borderLeftColor: '#008069',
    },
    bookingCardHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 16,
    },
    vehicleInfo: {
        flexDirection: 'row',
        alignItems: 'center',
        flex: 1,
    },
    vehicleName: {
        fontSize: 16,
        fontWeight: '600',
        color: '#333',
        flexShrink: 1,
    },
    plateText: {
        fontSize: 13,
        color: '#666',
        marginTop: 2,
    },
    statusBadge: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingHorizontal: 12,
        paddingVertical: 6,
        borderRadius: 16,
        marginLeft: 8,
    },
    statusText: {
        fontSize: 12,
        fontWeight: '600',
        marginLeft: 4,
        textTransform: 'capitalize',
    },
    bookingCardBody: {
        marginBottom: 16,
    },
    locationRow: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: 8,
    },
    locationText: {
        fontSize: 14,
        color: '#666',
        marginLeft: 10,
        flex: 1,
    },
    arrowContainer: {
        marginLeft: 8,
        marginBottom: 8,
    },
    bookingCardFooter: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingTop: 16,
        borderTopWidth: 1,
        borderTopColor: '#f0f0f0',
        gap: 20,
    },
    dateTimeInfo: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 6,
    },
    dateTimeInfoText: {
        fontSize: 14,
        color: '#666',
        fontWeight: '500',
    },

    // ==================== VEHICLE IMAGES ====================
    vehicleImage: {
        width: 56,
        height: 56,
        borderRadius: 28,
    },
    vehicleImageLarge: {
        width: 80,
        height: 80,
        borderRadius: 40,
    },
    vehicleIconContainerLarge: {
        width: 80,
        height: 80,
        borderRadius: 40,
        backgroundColor: '#E8F5E9',
        justifyContent: 'center',
        alignItems: 'center',
    },

    // ==================== FORM ELEMENTS ====================
    formGroup: {
        marginBottom: 20,
    },
    labelContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: 8,
    },
    formLabel: {
        fontSize: 14,
        fontWeight: '600',
        color: '#333333',
    },
    requiredStar: {
        color: '#FF3B30',
        fontSize: 14,
        marginLeft: 2,
    },
    optionalText: {
        fontSize: 12,
        color: '#8E8E93',
        marginLeft: 4,
        fontStyle: 'italic',
    },
    inputContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#F8F9FA',
        borderRadius: 10,
        paddingHorizontal: 12,
        borderWidth: 1,
        borderColor: '#E9EDEF',
    },
    textInput: {
        flex: 1,
        paddingVertical: 12,
        fontSize: 15,
        color: '#333333',
        minHeight: 44,
    },
    inputIcon: {
        marginRight: 8,
    },
    inputUnit: {
        fontSize: 14,
        color: '#8E8E93',
        marginLeft: 8,
    },
    
    // Date Time Inputs (Updated for WhatsApp style)
    dateTimeInput: {
        flex: 1,
        backgroundColor: '#F8F9FA',
        borderWidth: 1,
        borderColor: '#E9EDEF',
        borderRadius: 10,
        paddingHorizontal: 16,
        paddingVertical: 14,
        flexDirection: 'row',
        alignItems: 'center',
    },
    dateTimeText: {
        fontSize: 14,
        color: '#333333',
        marginLeft: 12,
        fontWeight: '500',
    },
    
    // WhatsApp-style date time button
    dateTimeButton: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#F8F9FA',
        borderRadius: 10,
        paddingHorizontal: 16,
        paddingVertical: 14,
        borderWidth: 1,
        borderColor: '#E9EDEF',
    },
    dateTimeButtonText: {
        flex: 1,
        fontSize: 15,
        color: '#333333',
        marginLeft: 12,
    },
    
    // Text Area (Updated)
    textAreaContainer: {
        backgroundColor: '#F8F9FA',
        borderRadius: 10,
        borderWidth: 1,
        borderColor: '#E9EDEF',
    },
    textAreaInput: {
        padding: 16,
        fontSize: 15,
        color: '#333333',
        minHeight: 100,
        textAlignVertical: 'top',
    },
    
    descriptionInput: {
        flex: 1,
        padding: 16,
        fontSize: 16,
        color: '#000000',
        minHeight: 100,
        textAlignVertical: 'top',
    },
    
    dateButton: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#F8F9FA',
        borderRadius: 10,
        padding: 16,
    },
    dateButtonText: {
        flex: 1,
        fontSize: 16,
        color: '#000000',
    },
    dateButtonPlaceholder: {
        color: '#8E8E93',
    },
    buttonIcon: {
        marginRight: 8,
    },
    documentButton: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#F8F9FA',
        borderRadius: 12,
        padding: 12,
    },
    documentButtonText: {
        flex: 1,
        fontSize: 16,
        color: '#000000',
    },
    documentInfo: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'flex-start',
        backgroundColor: '#E8F5E9',
        padding: 12,
        borderRadius: 8,
        marginTop: 8,
        width: '75%',
        marginRight: 12,
        paddingRight: 30,
    },
    documentRow: {
        flexDirection: 'row',
        alignItems: 'center',
        flex: 1,
    },
    documentName: {
        fontSize: 12,
        color: '#008069',
        marginLeft: 8,
        flex: 1,
    },
    removeDocumentButton: {
        padding: 4,
    },

    // ==================== BOOKING MODAL SPECIFIC (UPDATED) ====================
    // WhatsApp-style selected user
    selectedUserCard: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        backgroundColor: '#E8F5E9',
        borderRadius: 10,
        padding: 12,
        borderWidth: 1,
        borderColor: '#D1E7DD',
    },
    selectedUserContent: {
        flexDirection: 'row',
        alignItems: 'center',
        flex: 1,
    },
    selectedUserAvatar: {
        width: 44,
        height: 44,
        borderRadius: 22,
        backgroundColor: '#008069',
        alignItems: 'center',
        justifyContent: 'center',
        marginRight: 12,
    },
    selectedUserAvatarText: {
        color: '#FFFFFF',
        fontWeight: '600',
        fontSize: 16,
    },
    selectedUserInfo: {
        flex: 1,
    },
    selectedUserName: {
        fontSize: 15,
        fontWeight: '600',
        color: '#008069',
        marginBottom: 2,
    },
    selectedUserEmail: {
        fontSize: 13,
        color: '#666666',
    },
    removeUserButton: {
        padding: 8,
    },
    
    // WhatsApp-style search
    searchButton: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        backgroundColor: '#F8F9FA',
        borderRadius: 10,
        paddingHorizontal: 16,
        paddingVertical: 14,
        borderWidth: 1,
        borderColor: '#E9EDEF',
        borderStyle: 'dashed',
    },
    searchButtonText: {
        flex: 1,
        fontSize: 15,
        color: '#333333',
        marginLeft: 12,
    },
    
    // WhatsApp-style search container
    searchContainer: {
        marginTop: 12,
    },
    searchInputContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#F8F9FA',
        borderRadius: 20,
        paddingHorizontal: 16,
        paddingVertical: 10,
        borderWidth: 1,
        borderColor: '#E9EDEF',
        marginBottom: 8,
    },
    
    loadingContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        padding: 12,
        backgroundColor: '#f8f8f8',
        borderRadius: 12,
        marginTop: 8,
    },
    loadingText: {
        marginLeft: 10,
        color: '#666',
        fontSize: 14,
    },
    
    // WhatsApp-style results list
    resultsList: {
        maxHeight: 200,
        backgroundColor: '#FFFFFF',
        borderRadius: 10,
        borderWidth: 1,
        borderColor: '#E9EDEF',
    },
    userResult: {
        flexDirection: 'row',
        alignItems: 'center',
        padding: 12,
        borderBottomWidth: 1,
        borderBottomColor: '#F0F0F0',
    },
    resultAvatar: {
        width: 40,
        height: 40,
        borderRadius: 20,
        backgroundColor: '#25D366',
        alignItems: 'center',
        justifyContent: 'center',
        marginRight: 12,
    },
    resultAvatarText: {
        color: '#FFFFFF',
        fontWeight: '600',
        fontSize: 14,
    },
    resultInfo: {
        flex: 1,
    },
    resultName: {
        fontSize: 14,
        fontWeight: '600',
        color: '#333333',
        marginBottom: 2,
    },
    resultEmail: {
        fontSize: 12,
        color: '#8E8E93',
    },
    
    // WhatsApp-style no results
    noResults: {
        alignItems: 'center',
        justifyContent: 'center',
        padding: 20,
        backgroundColor: '#FFFFFF',
        borderRadius: 10,
        borderWidth: 1,
        borderColor: '#E9EDEF',
    },
    noResultsText: {
        fontSize: 14,
        color: '#8E8E93',
        marginTop: 8,
    },

    // ==================== MODAL STYLES (UPDATED) ====================
    // WhatsApp-style modal overlay
    modalOverlay: {
        flex: 1,
        backgroundColor: 'rgba(0, 0, 0, 0.8)',
        justifyContent: 'flex-end',
    },
    keyboardAvoidingView: {
        width: '100%',
    },
    
    // WhatsApp-style modal container
    modalContainer: {
        backgroundColor: '#F0F2F5',
        borderTopLeftRadius: 20,
        borderTopRightRadius: 20,
        maxHeight: screenHeight * 0.9,
        width: '100%',
    },
    
    // WhatsApp-style modal header
    modalHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        backgroundColor: '#008069',
        paddingTop: Platform.OS === 'ios' ? 20 : 40,
        paddingBottom: 16,
        paddingHorizontal: 16,
        borderTopLeftRadius: 20,
        borderTopRightRadius: 20,
    },
    headerLeft: {
        flexDirection: 'row',
        alignItems: 'center',
        flex: 1,
    },
    headerTitleContainer: {
        flex: 1,
    },
    modalTitle: {
        fontSize: 18,
        fontWeight: '700',
        color: '#FFFFFF',
        marginBottom: 2,
    },
    modalSubtitle: {
        fontSize: 13,
        color: 'rgba(255, 255, 255, 0.8)',
    },
    headerIconButton: {
        width: 36,
        height: 36,
        borderRadius: 18,
        backgroundColor: 'rgba(255, 255, 255, 0.1)',
        alignItems: 'center',
        justifyContent: 'center',
        marginLeft: 8,
    },
    
    modalScrollContent: {
        paddingBottom: 30,
    },
    
    // WhatsApp-style section
    section: {
        backgroundColor: '#FFFFFF',
        borderRadius: 12,
        marginHorizontal: 16,
        marginTop: 16,
        padding: 16,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.05,
        shadowRadius: 2,
        elevation: 2,
    },
    sectionHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: 16,
        paddingBottom: 12,
        borderBottomWidth: 1,
        borderBottomColor: '#F0F0F0',
    },
    
    // Modal close button (legacy)
    modalCloseButton: {
        width: 40,
        height: 40,
        borderRadius: 20,
        backgroundColor: '#F5F5F5',
        alignItems: 'center',
        justifyContent: 'center',
    },
    
    downloadButton: {
        width: 40,
        height: 40,
        borderRadius: 20,
        backgroundColor: '#F5F5F5',
        alignItems: 'center',
        justifyContent: 'center',
    },
    
    // WhatsApp-style action buttons
    modalActions: {
        flexDirection: 'row',
        paddingHorizontal: 16,
        paddingTop: 24,
        paddingBottom: Platform.OS === 'ios' ? 40 : 20,
    },
    cancelButton: {
        flex: 1,
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: '#FFFFFF',
        paddingVertical: 14,
        borderRadius: 25,
        borderWidth: 1,
        borderColor: '#E9EDEF',
        marginRight: 8,
    },
    cancelButtonText: {
        fontSize: 16,
        fontWeight: '600',
        color: '#666666',
    },
    submitButton: {
        flex: 2,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: '#008069',
        paddingVertical: 14,
        borderRadius: 25,
        gap: 8,
        shadowColor: '#008069',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.3,
        shadowRadius: 4,
        elevation: 3,
    },
    submitButtonDisabled: {
        backgroundColor: '#A0D9B4',
        shadowOpacity: 0,
        elevation: 0,
    },
    submitButtonText: {
        fontSize: 16,
        fontWeight: '600',
        color: '#FFFFFF',
    },
    
    // Legacy modal buttons (keeping for compatibility)
    modalButtons: {
        flexDirection: 'row',
        gap: 12,
        marginTop: 24,
    },
    modalCancelButton: {
        flex: 1,
        backgroundColor: '#F5F5F5',
        padding: 16,
        borderRadius: 12,
        alignItems: 'center',
        borderWidth: 1,
        borderColor: '#E9EDEF',
    },
    modalCancelText: {
        fontSize: 16,
        color: '#666',
        fontWeight: '600',
    },
    modalSubmitButton: {
        flex: 1,
        backgroundColor: '#008069',
        padding: 16,
        borderRadius: 12,
        alignItems: 'center',
        justifyContent: 'center',
        minHeight: 52,
    },
    modalSubmitButtonDisabled: {
        backgroundColor: '#A0D9B4',
    },
    modalSubmitText: {
        fontSize: 16,
        color: '#FFFFFF',
        fontWeight: '600',
    },

    // ==================== LOG CARDS ====================
    logCard: {
        backgroundColor: '#FFFFFF',
        padding: 16,
        borderRadius: 12,
        marginBottom: 12,
        borderWidth: 1,
        borderColor: '#E9EDEF',
    },
    logHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'flex-start',
        marginBottom: 12,
    },
    logHeaderLeft: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 8,
    },
    logCost: {
        fontSize: 18,
        fontWeight: '700',
        color: '#008069',
    },
    logDate: {
        fontSize: 12,
        color: '#666',
    },
    logQuantity: {
        fontSize: 14,
        color: '#666',
        marginTop: 2,
    },
    logDescription: {
        fontSize: 14,
        color: '#000000',
        lineHeight: 20,
        marginBottom: 12,
    },
    logDetails: {
        gap: 8,
    },
    logDetailRow: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 6,
    },
    logDetail: {
        fontSize: 13,
        color: '#666',
    },
    fuelDetails: {
        flexDirection: 'row',
        justifyContent: 'center',
        backgroundColor: '#F8F9FA',
        padding: 12,
        borderRadius: 8,
        marginBottom: 12,
    },
    fuelDetailItem: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 6,
    },
    fuelDetailValue: {
        fontSize: 16,
        fontWeight: '600',
        color: '#008069',
    },
    documentSection: {
        marginTop: 12,
        paddingTop: 12,
        borderTopWidth: 1,
        borderTopColor: '#F0F0F0',
    },
    documentCard: {
        backgroundColor: '#F8F9FA',
        borderRadius: 12,
        padding: 12,
        borderWidth: 1,
        borderColor: '#E8E8E8',
        display: 'flex',
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
    },
    documentTextContainer: {
        marginLeft: 0,
        marginTop: 3,
    },
    documentActions: {
        flexDirection: 'row',
        gap: 8,
    },
    viewButton: {
        height: 45,
        width: 45,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        borderRadius: 8,
        backgroundColor: '#FFFFFF',
        borderWidth: 1,
        borderColor: '#008069',
    },
    emptyStateContainer: {
        alignItems: 'center',
        paddingVertical: 60,
        paddingHorizontal: 20,
        backgroundColor: '#F0F2F5',
    },
    emptyIconCircle: {
        width: 100,
        height: 100,
        borderRadius: 50,
        backgroundColor: '#E8F5E9',
        alignItems: 'center',
        justifyContent: 'center',
        marginBottom: 20,
    },
    emptyStateCard: {
        backgroundColor: '#fff',
        borderRadius: 20,
        padding: 32,
        alignItems: 'center',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.1,
        shadowRadius: 12,
        elevation: 4,
        width: '100%',
        maxWidth: 400,
    },
    emptyIconContainer: {
        width: 120,
        height: 120,
        borderRadius: 60,
        backgroundColor: '#F7FAFC',
        alignItems: 'center',
        justifyContent: 'center',
        marginBottom: 24,
    },
    emptyStateTitle: {
        fontSize: 20,
        fontWeight: '600',
        color: '#333',
        marginBottom: 8,
        textAlign: 'center',
    },
    emptyStateText: {
        fontSize: 15,
        color: '#666',
        textAlign: 'center',
        lineHeight: 22,
    },
    emptyStateSubtext: {
        fontSize: 14,
        color: '#999',
        textAlign: 'center',
    },
    emptyStateMessage: {
        fontSize: 16,
        color: '#4A5568',
        textAlign: 'center',
        lineHeight: 24,
        marginBottom: 8,
    },
    emptyState: {
        alignItems: 'center',
        paddingVertical: 40,
    },

    // ==================== LISTS ====================
    cabsListContent: {
        padding: 16,
    },
    searchBtn: {
        backgroundColor: '#00d285',
        padding: 16,
        borderRadius: 12,
        alignItems: 'center',
        marginTop: 20,
        shadowColor: '#00d285',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.3,
        shadowRadius: 8,
        elevation: 3,
    },
    searchBtnText: {
        color: '#fff',
        fontSize: 16,
        fontWeight: '600',
    },
    disabledBtn: {
        opacity: 0.5,
        shadowOpacity: 0,
        elevation: 0,
    },
    formSection: {
        backgroundColor: '#FFFFFF',
        borderRadius: 12,
        padding: 16,
        marginBottom: 16,
        marginHorizontal: 16,
        elevation: 2,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.1,
        shadowRadius: 2,
    },
    formInput: {
        backgroundColor: '#F8F9FA',
        borderWidth: 1.5,
        borderColor: '#E9EDEF',
        borderRadius: 12,
        paddingHorizontal: 16,
        paddingVertical: 14,
        fontSize: 16,
        color: '#333',
    },
    optionsContainer: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        gap: 8,
        marginTop: 4,
    },
    optionButton: {
        paddingHorizontal: 16,
        paddingVertical: 10,
        borderRadius: 20,
        backgroundColor: '#F8F9FA',
        borderWidth: 1.5,
        borderColor: '#E9EDEF',
        minWidth: 100,
        alignItems: 'center',
    },
    optionButtonSelected: {
        backgroundColor: '#E8F5E9',
        borderColor: '#008069',
    },
    optionButtonText: {
        fontSize: 14,
        fontWeight: '500',
        color: '#666',
    },
    optionButtonTextSelected: {
        color: '#008069',
        fontWeight: '600',
    },
    documentGroup: {
        marginBottom: 16,
    },
    documentSelected: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#E8F5E9',
        borderRadius: 12,
        padding: 12,
        borderWidth: 1.5,
        borderColor: '#008069',
        gap: 12,
    },
    photoButton: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: '#F8F9FA',
        borderRadius: 12,
        padding: 16,
        borderWidth: 1.5,
        borderColor: '#E9EDEF',
        borderStyle: 'dashed',
        gap: 12,
        marginBottom: 12,
    },
    photoButtonText: {
        fontSize: 16,
        color: '#008069',
        fontWeight: '500',
    },
    photosContainer: {
        gap: 8,
        marginTop: 8,
    },
    photoItem: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#F8F9FA',
        borderRadius: 12,
        padding: 12,
        borderWidth: 1,
        borderColor: '#E9EDEF',
        gap: 12,
    },
    photoName: {
        fontSize: 14,
        color: '#333',
        flex: 1,
    },
    
    scrollView: {
        flex: 1,
    },
    
    photoScrollContent: {
        paddingVertical: 8,
    },
    photoSlot: {
        width: IMAGE_SLOT_WIDTH,
        height: IMAGE_SLOT_WIDTH,
        borderRadius: 12,
        borderWidth: 2,
        borderColor: '#E9EDEF',
        borderStyle: 'dashed',
        marginRight: 12,
        overflow: 'hidden',
        backgroundColor: '#F8F9FA',
        position: 'relative',
    },
    emptyPhotoSlot: {
        flex: 1,
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: '#F8F9FA',
    },
    photoImage: {
        width: '100%',
        height: '100%',
    },
    removePhotoButton: {
        position: 'absolute',
        top: 6,
        right: 6,
        width: 24,
        height: 24,
        borderRadius: 12,
        backgroundColor: 'rgba(0, 0, 0, 0.6)',
        alignItems: 'center',
        justifyContent: 'center',
        zIndex: 1,
    },
    addPhotoText: {
        fontSize: 12,
        color: '#008069',
        marginTop: 4,
        fontWeight: '500',
    },
    inputGroup: {
        marginBottom: 16,
    },
    label: {
        fontSize: 14,
        fontWeight: '600',
        color: '#333',
        marginBottom: 8,
    },
    input: {
        backgroundColor: '#F8F9FA',
        borderWidth: 1.5,
        borderColor: '#E9EDEF',
        borderRadius: 10,
        paddingHorizontal: 16,
        paddingVertical: 14,
        fontSize: 16,
        color: '#333',
    },
    row: {
        flexDirection: 'row',
    },
    documentIconContainer: {
        width: 40,
        height: 40,
        borderRadius: 8,
        backgroundColor: '#E8F5E9',
        alignItems: 'center',
        justifyContent: 'center',
        marginRight: 12,
    },
    documentTitle: {
        fontSize: 15,
        fontWeight: '600',
        color: '#333',
        marginBottom: 2,
    },
    documentSubtitle: {
        fontSize: 13,
        color: '#666',
    },
    buttonContainer: {
        paddingHorizontal: 16,
        marginTop: 24,
        marginBottom: 30,
    },
    updateButtonDisabled: {
        backgroundColor: '#A0A0A0',
        shadowOpacity: 0,
        elevation: 0,
    },
    updateVehicleHeader: {
        backgroundColor: '#008069',
        paddingTop: Platform.OS === 'ios' ? 50 : 40,
        paddingBottom: 16,
        paddingHorizontal: 16,
        elevation: 4,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 3,
    },
    updateVehicleHeaderContent: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
    },
    updateVehicleHeaderTitleContainer: {
        flex: 1,
        textAlign: 'center',
        alignItems: 'center',
    },
    updateVehicleHeaderTitle: {
        fontSize: 20,
        fontWeight: '700',
        color: '#FFFFFF',
        marginBottom: 2,
    },
    updateVehicleHeaderSubtitle: {
        fontSize: 13,
        color: 'rgba(255, 255, 255, 0.8)',
    },
    headerSpacer: {
        width: 40,
    },
    updateVehicleScrollContent: {
        paddingBottom: 100,
    },
    updateVehicleSection: {
        backgroundColor: '#FFFFFF',
        marginHorizontal: 16,
        marginTop: 16,
        borderRadius: 16,
        padding: 20,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.05,
        shadowRadius: 3,
        elevation: 2,
    },
    sectionHeaderRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 20,
    },
    sectionHeaderLeft: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    updateVehicleSectionIconContainer: {
        width: 44,
        height: 44,
        borderRadius: 12,
        backgroundColor: '#E8F5E9',
        alignItems: 'center',
        justifyContent: 'center',
        marginRight: 12,
    },
    updateVehicleSectionTitle: {
        fontSize: 18,
        fontWeight: '700',
        color: '#1A1A1A',
        marginBottom: 2,
    },
    updateVehicleSectionSubtitle: {
        fontSize: 13,
        color: '#666',
    },
    photoIndexBadge: {
        position: 'absolute',
        bottom: 6,
        left: 6,
        backgroundColor: 'rgba(0, 0, 0, 0.7)',
        borderRadius: 12,
        paddingHorizontal: 8,
        paddingVertical: 4,
    },
    photoIndexText: {
        color: '#fff',
        fontSize: 11,
        fontWeight: '600',
    },
    photoSlotNumber: {
        position: 'absolute',
        bottom: 8,
        fontSize: 10,
        color: '#999',
        fontWeight: '600',
    },
    halfWidth: {
        flex: 1,
    },
    required: {
        color: '#FF3B30',
    },
    inputWrapper: {
        backgroundColor: '#F8F9FA',
        borderWidth: 1.5,
        borderColor: '#E9EDEF',
        borderRadius: 12,
        overflow: 'hidden',
    },
    updateVehicleDocumentIconContainer: {
        width: 48,
        height: 48,
        borderRadius: 12,
        backgroundColor: '#E8F5E9',
        alignItems: 'center',
        justifyContent: 'center',
        marginRight: 14,
    },
    updateVehicleDocumentTitle: {
        fontSize: 14,
        fontWeight: '600',
        color: '#333',
        marginBottom: 4,
    },
    updateVehicleDocumentSubtitle: {
        fontSize: 13,
        color: '#666',
    },
    updateVehicleBottomContainer: {
        position: 'absolute',
        bottom: 0,
        left: 0,
        right: 0,
        backgroundColor: '#FFFFFF',
        paddingHorizontal: 16,
        paddingTop: 16,
        paddingBottom: Platform.OS === 'ios' ? 34 : 16,
        borderTopWidth: 1,
        borderTopColor: '#E9EDEF',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: -2 },
        shadowOpacity: 0.1,
        shadowRadius: 8,
        elevation: 8,
    },
    documentsContainer: {
        gap: 12,
    },

    documentDownloadButton: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#F8F9FA',
        borderRadius: 12,
        padding: 16,
        borderWidth: 1,
        borderColor: '#E9EDEF',
    },

    documentIconWrapper: {
        width: 48,
        height: 48,
        borderRadius: 24,
        backgroundColor: '#FFFFFF',
        justifyContent: 'center',
        alignItems: 'center',
        marginRight: 12,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.05,
        shadowRadius: 4,
        elevation: 2,
    },

    noDocumentsContainer: {
        alignItems: 'center',
        justifyContent: 'center',
        paddingVertical: 32,
        paddingHorizontal: 16,
    },

    noDocumentsText: {
        fontSize: 16,
        fontWeight: '600',
        color: '#718096',
        marginTop: 12,
    },

    noDocumentsSubtext: {
        fontSize: 14,
        color: '#A0AEC0',
        marginTop: 4,
        textAlign: 'center',
    },
    documentPreviewContainer: {
        marginBottom: 12,
    },

    documentNameContainer: {
        marginTop: 4,
    },

    documentNameText: {
        fontSize: 13,
        fontWeight: '500',
        color: '#008069',
        marginBottom: 2,
    },

    documentStatusText: {
        fontSize: 11,
        color: '#666',
        fontStyle: 'italic',
    },

    documentActionIcon: {
        width: 40,
        height: 40,
        alignItems: 'center',
        justifyContent: 'center',
        marginLeft: 8,
    },

    // Update this existing style:
    updateVehicleDocumentButton: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#FFFFFF',
        borderRadius: 12,
        padding: 16,
        marginBottom: 8,
        borderWidth: 1.5,
        borderColor: '#E9EDEF',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.05,
        shadowRadius: 2,
        elevation: 1,
    },
});